# generated by datamodel-codegen:
#   filename:  draft.json
#   timestamp: 2025-01-11T20:09:54+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, ConfigDict


class Recipients(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    to: List[str]
    cc: Optional[List[str]] = None
    bcc: Optional[List[str]] = None


class Attachment(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    name: str
    url: str


class Draft(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    recipients: Recipients
    subject: str
    content: str
    attachments: Optional[List[Attachment]] = None
