# generated by datamodel-codegen:
#   filename:  draft.json
#   timestamp: 2025-01-11T20:09:54+00:00

from __future__ import annotations

import logging
from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field

logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger(__name__)


class Recipients(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    to: List[str]
    cc: Optional[List[str]] = None
    bcc: Optional[List[str]] = None


class Attachment(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    name: str
    url: str


class Draft(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    thread_id: Optional[str] = Field(
        default=None,
        description="The thread id of the email, default is None for new email. For reply email, the thread id is the id of the email you want to reply to.",  # noqa: E501
    )
    recipients: Recipients
    subject: str
    content: str
    attachments: Optional[List[Attachment]] = None


class EmailMessageInput(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str | None = None
    thread_id: Optional[str] = Field(
        default=None,
        description="The thread id of the email, default is None for new email. For reply email, the thread id is the id of the email you want to reply to.",  # noqa: E501
    )
    recipients: Recipients
    subject: str
    content: str
    attachments: Optional[List[Attachment]] = None
